### ISSUE TITLE
vscode extension fails with new refactoring "move to file"

### ISSUE THREAD

**Issue by SantoJambit** [mdx-js/mdx-analyzer#420]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

1.8.2

### Steps to reproduce

- Install the extension
- create an .mdx file and two .ts files
- try to move something from one ts file to another via the new refactoring "move to file"
- observe the error shown by vscode

### Expected behavior

vscode should show the file selection popup (it does without the extension installed)

### Actual behavior

An error pops up:

> <semantic> TypeScript Server Error (5.4.2)
Debug Failure. File /.../file.mdx has unknown extension.
Error: Debug Failure. File /.../file.mdx has unknown extension.
    at extensionFromPath (/.../node_modules/typescript/lib/tsserver.js:21381:39)
    at /.../node_modules/typescript/lib/tsserver.js:147260:33
    at mapDefined (/.../node_modules/typescript/lib/tsserver.js:2680:22)
    at Proxy.getMoveToRefactoringFileSuggestions (/.../node_modules/typescript/lib/tsserver.js:147259:19)
    at IpcIOSession.getMoveToRefactoringFileSuggestions (/.../node_modules/typescript/lib/tsserver.js:187171:41)
    at getMoveToRefactoringFileSuggestions (/.../node_modules/typescript/lib/tsserver.js:185370:43)
    at /.../node_modules/typescript/lib/tsserver.js:187524:69
    at IpcIOSession.executeWithRequestId (/.../node_modules/typescript/lib/tsserver.js:187516:14)
    at IpcIOSession.executeCommand (/.../node_modules/typescript/lib/tsserver.js:187524:29)
    at IpcIOSession.onMessage (/.../node_modules/typescript/lib/tsserver.js:187566:51)
    at process.<anonymous> (/.../node_modules/typescript/lib/tsserver.js:189175:14)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)

### Runtime

Other (please specify in steps to reproduce)

### Package manager

Other (please specify in steps to reproduce)

### OS

Linux

### Build and bundle tools

Other (please specify in steps to reproduce)

**Comment by johnsoncodehk** [comment]
This is also a debug error encountered by @Princesseuh in astro language tools. It needs to be solved upstream. I will open an issue to TypeScript.

**Comment by Princesseuh** [comment]
Yep, here's the corresponding issue https://github.com/withastro/language-tools/issues/812

**Comment by louisgv** [comment]
This is somewhat relevant to #413 - downgrading to 1.7.3 worked
