### ISSUE TITLE
Crash in VS Code

### ISSUE THREAD

**Issue by JonnyBurger** [mdx-js/mdx-analyzer#481]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

1.8.11

### Steps to reproduce

Open a MDX in VS Code

### Expected behavior

Crash

### Actual behavior

```
[Info  - 10:27:07] Connection to server got closed. Server will restart.
true
/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:41833
  const rootExpression = (_a = sourceFile.statements[0]) == null ? void 0 : _a.expression;
                                                    ^

TypeError: Cannot read properties of undefined (reading '0')
    at convertConfigFileToObject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:41833:53)
    at parseOwnConfigOfJsonSourceFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:42667:16)
    at parseConfig (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:42566:97)
    at parseJsonConfigFileContentWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:42294:24)
    at Object.parseJsonSourceFileConfigFileContent (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:42263:18)
    at a (/Users/jonathanburger/.vscode/extensions/unifiedjs.vscode-mdx-1.8.11/out/language-server.js:897:19013)
    at /Users/jonathanburger/.vscode/extensions/unifiedjs.vscode-mdx-1.8.11/out/language-server.js:897:18633
    at $fe (/Users/jonathanburger/.vscode/extensions/unifiedjs.vscode-mdx-1.8.11/out/language-server.js:85:5357)
    at d (/Users/jonathanburger/.vscode/extensions/unifiedjs.vscode-mdx-1.8.11/out/language-server.js:85:12248)
    at S (/Users/jonathanburger/.vscode/extensions/unifiedjs.vscode-mdx-1.8.11/out/language-server.js:85:12018)

```

### Affected runtime and version

code --version: 1.94.0 d78a74bcdfad14d5d3b1b782f87255d802b57511 arm64

### Build and bundle tools

Docusaurus

**Comment by remcohaszing** [comment]
Please provide a repo to reproduce the issue.

**Comment by bradleyayers** [comment]
Are you able to share the tsconfig and directory/file structure? In my case this error came from it not being able to find the tsconfig.json for a given file, so both the tsconfig and the file structure is quite important. Or even better if you can link to the repo if it's public.

**Comment by j-machado** [comment]
It's happening quite often while using Cursor

**Comment by unional** [comment]
> [@TomONeill](https://github.com/TomONeill) if you're using TypeScript, and project references (in tsconfig.json files), make sure all the project references are paths to tsconfig.json (rather than directories). This works around the issue.

This workaround works.
But may be this issue should be reopened?
